version: '3'
services:
  dhbw-microservices-seminararbeit-mongo:
    image: "mongo"
    container_name: mongodb
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME:-test}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD:-test}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-co2Ampel}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - '~/mongo/data:/data/mongodb'
      - './init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
    hostname: ${MONGO_HOSTNAME:-localhost}
