apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 4001
      targetPort: 4001