version: '3'
services:
  dhbw-microservices-seminararbeit-mongo:
    image: "mongo"
    container_name: mongodb
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-co2Ampel}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - '~/mongo/data:/data/mongodb'
      - './mongodb-initdb.sh:/docker-entrypoint-initdb.d/mongodb-initdb.sh'
    hostname: ${MONGO_HOSTNAME:-localhost}