apiVersion: apps/v1
kind: Deployment
metadata:
  name: displaydata
  labels:
    app: displaydata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: displaydata
  template:
    metadata:
      labels:
        app: displaydata
    spec:
      containers:
        - name: displaydata
          imagePullPolicy: Always
          image: replace/me/displaydata
          env:
            - name: MONGO_INITDB_USERNAME
              value: 'test'
            - name: MONGO_INITDB_PASSWORD
              value: 'test'
            - name: MONGO_INITDB_DATABASE
              value: 'co2Ampel'
            - name: MONGO_HOSTNAME
              value: 'mongodb'
            - name: MONGO_PORT
              value: '27017'