apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: displaydata
spec:
  rules:
  - host: timostroehlein.microservices-seminararbeit.com
    http:
      paths:
      - path: /data
        pathType: Prefix
        backend:
          service:
            name: displaydata
            port:
              number: 4001